package com.swjeon.pethealthcaremanager.server.Entity;

//auto-generated by groovy script

import com.swjeon.pethealthcaremanager.server.Entity.IdClass.ChatMemberIdClass;
import lombok.*;
import jakarta.persistence.*;

import java.time.LocalDateTime;


@Entity
@Table(name = "chat_member")
@IdClass(ChatMemberIdClass.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ChatMemberEntity {
  @Id
  @Column(name = "ROOM_ID")
  private int roomId;
  @Id
  @Column(name = "MEMBER_ID")
  private String memberId;
}
