package com.swjeon.pethealthcaremanager.server.Entity;

//auto-generated by groovy script

import lombok.Getter;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.time.LocalDateTime;


@Entity
@Table(name = "chat_member")
@Getter
@NoArgsConstructor
public class ChatMemberEntity {

  @Column(name = "ROOM_ID")
  private long roomId;
  @Column(name = "MEMBER_ID")
  private String memberId;

}
