package com.swjeon.pethealthcaremanager.server.Entity;

//auto-generated by groovy script

import com.swjeon.pethealthcaremanager.server.Entity.IdClass.ChatMemberIdClass;
import lombok.Getter;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import lombok.Setter;

import java.time.LocalDateTime;


@Entity
@Table(name = "chat_member")
@IdClass(ChatMemberIdClass.class)
@Getter
@Setter
@NoArgsConstructor
public class ChatMemberEntity {
  @Id
  @Column(name = "ROOM_ID")
  private int roomId;
  @Id
  @Column(name = "MEMBER_ID")
  private String memberId;

}
