package com.swjeon.pethealthcaremanager.server.Entity;

//auto-generated by groovy script

import lombok.Getter;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import lombok.Setter;

import java.time.LocalDateTime;


@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class UsersEntity {

  @Id
  @Column(name = "ID")
  private String id;
  @Column(name = "PW")
  private String pw;
  @Column(name = "NICKNAME")
  private String nickname;

}
