package com.swjeon.pethealthcaremanager.server.Entity;

//auto-generated by groovy script

import com.swjeon.pethealthcaremanager.server.Repository.PetRepository;
import com.swjeon.pethealthcaremanager.server.dto.PetDTO;
import com.swjeon.pethealthcaremanager.server.dto.UserDTO;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;


@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class UsersEntity {

  @Id
  @Column(name = "ID")
  private String id;
  @Column(name = "PW")
  private String pw;
  @Column(name = "NICKNAME")
  private String nickname;

  public UserDTO toDTO(PetRepository petRepository) {
    UserDTO userDTO = new UserDTO(id, pw);
    userDTO.setNickname(nickname);
    List<PetEntity> petEntities = petRepository.findByUserId(id);
    ArrayList<PetDTO> petDTOs = new ArrayList<>();
    for (PetEntity petEntity : petEntities) {
      petDTOs.add(petEntity.toDTO());
    }
    userDTO.setPets(petDTOs);
    return userDTO;
  }
}
