package com.swjeon.pethealthcaremanager.server.Entity;

//auto-generated by groovy script

import lombok.Getter;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.time.LocalDateTime;


@Entity
@Table(name = "user")
@Getter
@NoArgsConstructor
public class UserEntity {

  @Column(name = "ID")
  private String id;
  @Column(name = "PW")
  private String pw;
  @Column(name = "NICKNAME")
  private String nickname;

}
