CREATE TABLE USERS(
	ID VARCHAR(20) NOT NULL PRIMARY KEY,
	PW VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20)
);
CREATE TABLE CHAT_ROOM(
	ID INT AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE CHAT_MEMBER(
	ROOM_ID INT NOT NULL,
    MEMBER_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY(ROOM_ID, MEMBER_ID),
    FOREIGN KEY(ROOM_ID) REFERENCES CHAT_ROOM(ID)
	ON DELETE CASCADE,
    FOREIGN KEY(MEMBER_ID) REFERENCES USERS(ID)
	ON DELETE CASCADE
);
CREATE TABLE CHAT(
	CHAT_ID INT AUTO_INCREMENT PRIMARY KEY,
	ROOM_ID INT NOT NULL,
	WRITER_ID VARCHAR(20) NOT NULL,
	WRITE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONTENT JSON NULL,
	FOREIGN KEY(ROOM_ID) REFERENCES CHAT_ROOM(ID)
	ON DELETE CASCADE,
	FOREIGN KEY(WRITER_ID) REFERENCES USERS(ID)
	ON UPDATE CASCADE
);